# Generated by Django 4.2.6 on 2023-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=30, verbose_name='№ каталога')),
                ('performer', models.CharField(max_length=30, verbose_name='Исполнитель')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Хронометраж')),
                ('video_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип')),
                ('director', models.CharField(blank=True, max_length=30, null=True, verbose_name='Режиссёр')),
                ('screenwriter', models.CharField(blank=True, max_length=30, null=True, verbose_name='Сценарист')),
                ('composer', models.CharField(blank=True, max_length=30, null=True, verbose_name='Композитор')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('rutube_link', models.URLField(blank=True, null=True, verbose_name='RuTube')),
                ('yandex_link', models.URLField(blank=True, null=True, verbose_name='Яндекс')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='VK')),
                ('zen_link', models.URLField(blank=True, null=True, verbose_name='Дзен')),
                ('upc', models.CharField(blank=True, max_length=30, null=True, verbose_name='UPC')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Видеокаталог',
                'verbose_name_plural': 'Видеокаталоги',
            },
        ),
    ]
